###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: info
jwt_secret: 4EC1DD9BFF850EA2E259D246257FDF772187F741

server:
  read_buffer_size: 4096
  write_buffer_size: 4096

default_redirection_url: https://owncloud.example.com/
totp:
  issuer: example.com
  period: 30
  skew: 1

duo_api:
  hostname: api-0ab4cd08.duosecurity.com
  integration_key: DI4B6H08GA7TP3NCK14S
  secret_key: CGTtRpuQgnCGIhvutah3TjQxUpn4higIlolKFFds

authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  ldap:
     implementation: custom
     url: ldap://openldap
     start_tls: false
     tls:
       skip_verify: false
       minimum_version: TLS1.2
     base_dn: dc=example,dc=com
     username_attribute: uid
     additional_users_dn: ou=users
     users_filter: (&({username_attribute}={input})(objectClass=person))
     additional_groups_dn: ou=groups
     groups_filter: (&(member={dn})(objectclass=groupOfNames))
     group_name_attribute: cn
     mail_attribute: mail
     display_name_attribute: displayname
     user: cn=admin,dc=example,dc=com
     password: darwinism-unmarked-spring-gopher

access_control:
  default_policy: deny
  rules:
    - domain: owncloud.example.com
      policy: bypass

    - domain: ip.example.com
      policy: bypass

    - domain: "*.example.com"
      policy: bypass
      networks:
        - 1.2.3.4

    - domain: "*.example.com"
      policy: two_factor

session:
  name: authelia_session
  secret: 6C8BCD881E4CB3FF768D88BB191D0F2156E351AD
  expiration: 1h
  inactivity: 5m
  domain: example.com
  redis:
    host: redis
    port: 6379
    # password: authelia

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  mysql:
    host: 192.168.1.1
    port: 3306
    database: authelia
    username: authelia
    password: password

notifier:
  disable_startup_check: true
  smtp:
    host: smtp
    port: 25
    sender: authelia@example.com
    subject: "[Authelia] {title}"
    disable_require_tls: true
    tls:
      skip_verify: true
