<?php
$CONFIG = array (
  'instanceid' => 'somestring',
  'passwordsalt' => 'somestring',
  'secret' => 'somestring',
  'trusted_domains' =>
  array (
    0 => 'nextcloud.example.com',
  ),
  'trusted_proxies' =>
  array (
    0 => '192.168.1.1',
  ),
  'datadirectory' => '/mnt/data/horwood_owncloud/',
  'overwrite.cli.url' => 'https://owncloud.example.com',
  'dbtype' => 'mysql',
  'version' => '22.2.3.0',
  'dbname' => 'nextcloud',
  'dbhost' => '192.168.1.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'YourPassword',
  'logtimezone' => 'UTC',
  'logdateformat' => 'Y-m-d H:i:s',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'nextcloud',
  'mail_domain' => 'example.com',
  'mail_smtpport' => '25',
  'theme' => '',
  'filelocking.enabled' => 'true',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '192.168.1.1',
    'port' => 6379,
  ),
  'asset-pipeline.enabled' => false,
  'filesystem_check_changes' => '0',
  'trashbin_retention_obligation' => 'auto',
  'preview_max_scale_factor' => 1,
  'preview_max_x' => '2048',
  'preview_max_y' => '2048',
  'maintenance' => false,
  'loglevel' => 0,
  'htaccess.RewriteBase' => '/',
  'has_internet_connection' => true,
  'data-fingerprint' => 'Your FingerPrint',
  'log_rotate_size' => 52428800,
  'tempdirectory' => '/mnt/data/nc_temp',
  'htaccess.IgnoreFrontController' => true,
  'mail_sendmailmode' => 'smtp',
  'mail_smtphost' => 'smtp-relay.gmail.com',
  'mail_smtpsecure' => 'tls',
  'jpeg_quality' => '60',
  'mysql.utf8mb4' => true,
  'default_phone_region' => 'GB',
  'app_install_overwrite' =>
  array (
    0 => 'groupfolders',
    1 => 'previewgenerator',
  ),
  'enable_previews' => true,
  'enabledPreviewProviders' =>
  array (
    'OC\Preview\Movie',
    'OC\Preview\PNG',
    'OC\Preview\JPEG',
    'OC\Preview\GIF',
    'OC\Preview\BMP',
    'OC\Preview\XBitmap',
    'OC\Preview\MP3',
    'OC\Preview\MP4',
    'OC\Preview\TXT',
    'OC\Preview\MarkDown',
    'OC\Preview\PDF'
  ),
);
