version: '3.5'

# docker stack deploy --compose-file stack-proxy.yml proxy

networks:
  authelia:
  dashmachine:
  gogs:
  invoiceplane:
  jukebox:
  phpipam:
  phpmyadmin:
  pihole:
  pigallery2:
  unifi:

services:
  proxyv22:
    image: traefik:v2.2 # The official Traefik docker image
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.swarmMode=true"
    networks:
      - authelia
      - dashmachine
      - gogs
      - invoiceplane
      - jukebox
      - phpipam
      - phpmyadmin
      - pihole
      - pigallery2
      - unifi
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTP port
      - "8181:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
