version: '3.5'

# docker stack deploy --compose-file stack-phpmyadmin.yml phpmyadmin

# networks:

# volumes:

services:
  phpmyadmin:
    image: mhzawadi/phpmyadmin:dev
    volumes:
      - /mnt/data/config.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      - HOST_URL=mysql.example.com
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
      labels:
        - "traefik.http.routers.mysql.rule=Host(`mysql.example.com`)"
        - "traefik.http.routers.mysql.service=mysql"
        - "traefik.http.services.mysql.loadbalancer.server.port=80"
        - "traefik.http.middlewares.mysql.headers.SSLProxyHeaders.proto=X-Forwarded-Proto:https"
        - "traefik.http.middlewares.mysql.headers.customrequestheaders.x-forwarded-proto=https"
        - "traefik.http.middlewares.mysql.headers.customrequestheaders.x-forwarded-port=443"
        - "traefik.http.middlewares.mysql.headers.customrequestheaders.http-x-secure-request=true"
        - "traefik.http.routers.mysql.middlewares=mysql"
