version: '3.5'

# docker stack deploy --compose-file stack-dmarc-report.yml dmarc-report

networks:
  proxy_dmarc:
    external: true

services:
  dmarc-report:
    image: gutmensch/dmarc-report:latest
    environment:
      - "REPORT_DB_HOST=192.168.1.1"
      - "REPORT_DB_NAME=dmarc_report"
      - "REPORT_DB_USER=dmarc_report"
      - "REPORT_DB_PASS=somestring"
      - "PARSER_IMAP_SERVER_WITH_PORT=imap.gmail.com:993"
      - "PARSER_IMAP_USER=matt@example.com"
      - "PARSER_IMAP_PASS=weekwhnbfbyscsos"
      - "PARSER_IMAP_READ_FOLDER=dmarc-report"
      - "PARSER_IMAP_MOVE_FOLDER=Bin"
      - "PARSER_IMAP_SSL=1"
      - "PARSER_IMAP_TLS=0"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 90M
        reservations:
          cpus: '0.25'
          memory: 80M
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
      labels:
        - "traefik.docker.network=proxy_dmarc"
        - "traefik.http.routers.dmarc.rule=Host(`dmarc.example.com`)"
        - "traefik.http.routers.dmarc.service=dmarc"
        - "traefik.http.services.dmarc.loadbalancer.server.port=80"
