version: '3.5'

# docker stack deploy --compose-file stack-proxy.yml proxy

networks:
  pi_network:
  drone_runner:
    external: true

volumes:
  mariadb_10_4:

services:
  proxyv2:
    image: traefik:v2.0 # The official Traefik docker image
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.swarmMode=true"
    networks:
      - pi_network
      - drone_runner
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTP port
      - "8181:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
