version: '3.5'

# docker stack deploy --compose-file stack-dmarc.yml dmarc

# networks:

# volumes:

services:
  dmarc-report:
    image: "gutmensch/dmarc-report:latest"
    environment:
      - "REPORT_DB_HOST=192.168.1.1"
      - "REPORT_DB_NAME=dmarc_report"
      - "REPORT_DB_USER=dmarc_report"
      - "REPORT_DB_PASS=password"
      - "PARSER_IMAP_SERVER_WITH_PORT=imap.gmail.com:993"
      - "PARSER_IMAP_USER=dmarc@example.com"
      - "PARSER_IMAP_PASS=password"
      - "PARSER_IMAP_READ_FOLDER=dmarc-report"
      - "PARSER_IMAP_MOVE_FOLDER=Bin"
      - "PARSER_IMAP_SSL=1"
      - "PARSER_IMAP_TLS=0"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.http.routers.dmarc.rule=Host(`dmarc.example.com`)"
        - "traefik.http.routers.dmarc.service=dmarc"
        - "traefik.http.services.dmarc.loadbalancer.server.port=80"
