version: '3.5'

# docker stack deploy --compose-file stack-invoiceplane.yml invoiceplane

# networks:

volumes:
  invoiceplane_data:

configs:
  invoiceplane:
    external: true

services:
  invoiceplane:
    image: mhzawadi/invoiceplane
    volumes:
      - invoiceplane_data:/var/www/html/uploads
    environment:
      - TZ=Europe/London
      - MYSQL_HOST=192.168.1.1
      - MYSQL_USER=InvoicePlane
      - MYSQL_PASSWORD=password
      - MYSQL_DB=InvoicePlane
      - HOST_URL=ip.example.com
      - IP_URL=https://ip.example.com
      - DISABLE_SETUP=true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.http.routers.invoiceplane.rule=Host(`ip.example.com`)"
        - "traefik.http.routers.invoiceplane.service=invoiceplane"
        - "traefik.http.services.invoiceplane.loadbalancer.server.port=80"
    configs:
      - source: invoiceplane
        target: /var/www/html/ipconfig.php
        uid: "0"
        gid: "0"
        mode: 0444
