version: '3.5'

# docker stack deploy --compose-file stack-gogs.yml gogs;curl https://portainer.example.com/api/webhooks/59f48ae2-8be0-4d91-ae65-3926c129bb29

# networks:

configs:
  config.php:
    external: true

volumes:
  nextcloud:

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      labels:
        - traefik.enable=false
  notify_push:
    image: mhzawadi/notify_push
    ports:
      - "7867:7867"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      labels:
        - traefik.enable=false
    configs:
      - source: config.php
        target: /etc/nc_config.php
        uid: "0"
        gid: "0"
        mode: 0444
    volumes:
      - nextcloud:/data
