version: '3.5'

# docker stack deploy --compose-file stack-gogs.yml gogs

# networks:

volumes:
  gogs_data:

services:
  gogs:
    image: gogs/gogs-rpi
    networks:
      - proxy_gogs
    ports:
      - "2250:22"
    volumes:
      - gogs_data:/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.docker.network=proxy_gogs"
        - "traefik.http.routers.gogo.rule=Host(`gogs.example.com`)"
        - "traefik.http.routers.gogo.service=gogo"
        - "traefik.http.services.gogo.loadbalancer.server.port=3000"
