version: '3.5'

# docker stack deploy --compose-file stack-phpmyadmin.yml phpmyadmin

networks:
  proxy_pi_network:
    external: true

# volumes:

services:
  phpmyadmin:
    image: mhzawadi/phpmyadmin:v5.0.1.3
    networks:
      - proxy_pi_network
    volumes:
      - ./config.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      - HOST_URL=mysql.mydomain.com
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.http.routers.mysql.rule=Host(`mysql.mydomain.com`)"
        - "traefik.http.routers.mysql.service=mysql"
        - "traefik.http.services.mysql.loadbalancer.server.port=80"
      placement:
        constraints:
          - node.role == worker
