---

# docker stack deploy --compose-file stack-nextcloud.yml nextcloud

networks:
  proxy_nextcloud:
    external: true

configs:
  example_config.php:
    external: true

volumes:
  redis_data:
  nextcloud:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/var/data/example_owncloud'

services:
  redis:
    image: redis
    networks:
      - proxy_nextcloud
    ports:
      - "6379:6379"
    deploy:
      update_config:
        order: start-first
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      labels:
        - "traefik.enable=false"
    volumes:
      - redis_data:/data

  notify_push:
    image: miles170/notify_push:v1.3.0
    command: [ "/notify_push", "/etc/nc_config.php" ]
    networks:
      - proxy_nextcloud
    ports:
      - "7867:7867"
    deploy:
      update_config:
        order: start-first
      mode: global
      resources:
        limits:
          cpus: '0.50'
          memory: 30M
        reservations:
          cpus: '0.25'
          memory: 10M
      labels:
        - "traefik.enable=false"
    configs:
      - source: example_config.php
        target: /etc/nc_config.php
        uid: "0"
        gid: "0"
        mode: 0444
    volumes:
      - nextcloud:/data
  whiteboard:
    image: ghcr.io/nextcloud-releases/whiteboard:v1.5.5
    networks:
      - proxy_nextcloud
    environment:
      - NEXTCLOUD_URL=https://example.com
      - JWT_SECRET_KEY=20c9bc9b212abf7e89840bb890b030cc14f25587fc105647f973e6cddb7516c8
    deploy:
      update_config:
        order: start-first
      mode: replicated
      labels:
        - "dashboard.name=NC Whiteboard"
        - "dashboard.icon=si:excalidraw"
        - "traefik.http.routers.whiteboard.rule=Host(`whiteboard.example.com`)"
        - "traefik.http.routers.whiteboard.service=whiteboard"
        - "traefik.http.services.whiteboard.loadbalancer.server.port=3002"
        - "traefik.http.middlewares.whiteboard.headers.SSLProxyHeaders.proto=X-Forwarded-Proto:https"
        - "traefik.http.middlewares.whiteboard.headers.customrequestheaders.x-forwarded-proto=https"
        - "traefik.http.middlewares.whiteboard.headers.customrequestheaders.x-forwarded-port=443"
        - "traefik.http.middlewares.whiteboard.headers.customrequestheaders.http-x-secure-request=true"
        - "traefik.http.routers.whiteboard.middlewares=whiteboard"
y
