version: '3.5'

# docker stack deploy --compose-file stack-authelia.yml authelia

networks:
  proxy_authelia:
    external: true

volumes:
  authelia:
  ldap_data:
  ldap_config:

configs:
  authelia:
    external: true

services:
  authelia:
    image: authelia/authelia
    networks:
      - proxy_authelia
    ports:
      - "9091:9091"     # The HTTP port
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      labels:
        - "traefik.http.routers.authelia_api.rule=Host(`auth.mydomain.com`)"
        - "traefik.http.routers.authelia_api.service=authelia_api"
        - "traefik.http.services.authelia_api.loadbalancer.server.port=9091"
        - "traefik.http.services.authelia_api.loadbalancer.server.scheme=http"
    configs:
      - source: authelia
        target: /etc/authelia/configuration.yml
        uid: "0"
        gid: "0"
        mode: 0444

    volumes:
      - authelia:/etc/authelia/storage
  redis:
    image: redis
    networks:
      - proxy_authelia
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=false
  smtp:
    image: mhzawadi/postfix:v0.0.1
    networks:
     - proxy_authelia
    deploy:
     mode: replicated
     replicas: 1
     labels:
       - "traefik.enable=false"
    ports:
      - "25:25"
    environment:
      - POSTFIX_DOMAIN=mydomain.com
      - POSTFIX_RELAYHOST=[smtp-relay.gmail.com]:25
  openldap:
    image: osixia/openldap:1.3.0
    networks:
      - proxy_authelia
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "My Company"
      LDAP_DOMAIN: "mydomain.com"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "operate-corroding-status"
      LDAP_CONFIG_PASSWORD: "purveyor-unloving-overshoot"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.mydomain.com','ldap://ldap2.mydomain.com']"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    domainname: "mydomain.com"
    hostname: "mydomain.com"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      labels:
        - "traefik.enable=false"
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    networks:
      - proxy_authelia
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      labels:
        - "traefik.http.routers.phpldapadmin.rule=Host(`ldap.mydomain.com`)"
        - "traefik.http.routers.phpldapadmin.service=phpldapadmin"
        - "traefik.http.services.phpldapadmin.loadbalancer.server.port=80"
        - "traefik.http.services.phpldapadmin.loadbalancer.server.scheme=http"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
