---

# run this to make SECRET keys: openssl rand -hex 32
# in the janus.jcfg, edit line 2900 with server
# run this to import config into swarm: docker config create janus_config ./config/janus.jcfg
# docker stack deploy --compose-file stack-nextcloud-thpb.yml nextcloud

networks:
  proxy_nextcloud:
    external: true

configs:
  janus_config:
    external: true

services:
  signaling:
    image: ghcr.io/nextcloud-releases/aio-talk:latest
    networks:
      - proxy_nextcloud
    deploy:
      update_config:
        order: start-first
      mode: replicated
      replicas: 1
      labels:
        - "dashboard.name=NC signaling"
        - "dashboard.icon=si:nextcloud"
        - "traefik.http.routers.signaling.rule=Host(`signaling.example.com`)"
        - "traefik.http.routers.signaling.service=signaling"
        - "traefik.http.services.signaling.loadbalancer.server.port=8081"
        - "traefik.http.middlewares.signaling.headers.SSLProxyHeaders.proto=X-Forwarded-Proto:https"
        - "traefik.http.middlewares.signaling.headers.customrequestheaders.x-forwarded-proto=https"
        - "traefik.http.middlewares.signaling.headers.customrequestheaders.x-forwarded-port=443"
        - "traefik.http.middlewares.signaling.headers.customrequestheaders.http-x-secure-request=true"
        - "traefik.http.routers.signaling.middlewares=signaling"
    environment:
      - NC_DOMAIN=example.com
      - TALK_HOST=www.example.com
      - TALK_PORT=3478
      - TURN_SECRET=431b6fef0b08125c795f38a58646f23c99310d3074155893559631815cb6afa0
      - SIGNALING_SECRET=f21bc8ee8ba91f5f47d52887748b05bf845194b0c535654c671b086750a62d30
      - INTERNAL_SECRET=8a132606c54bcb89da1474ef81f608a6d18587f0ede65e43428f0dde2277d4c5
    configs:
      - source: janus_config
        target: /usr/local/etc/janus/janus.jcfg
        uid: "0"
        gid: "0"
        mode: 0444
