version: '3.5'

# docker stack deploy --compose-file stack-phpipam.yml phpipam

networks:
  proxy_phpipam:
    external: true

# volumes:

services:
  phpipam:
    image: mhzawadi/phpipam:v1.4.0.3
    networks:
      - proxy_phpipam
    environment:
      - TZ=Europe/London
      - MYSQL_HOST=mysql
      - MYSQL_USER=phpipam
      - MYSQL_PASSWORD=phpipamadmin
      - MYSQL_DB=phpipam
      - HOST_URL=ipam.mydomain.com
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.arch==arm64v8
      labels:
        - "traefik.http.routers.ipam.rule=Host(`ipam.mydomain.com`)"
        - "traefik.http.routers.ipam.service=ipam"
        - "traefik.http.services.ipam.loadbalancer.server.port=80"
