version: '3.5'

# docker stack deploy --compose-file stack-bitwarden.yml bitwarden

# networks:

volumes:
  bitwarden_data:
  bitwarden_ssl:

services:
  bitwarden:
    image: vaultwarden/server
    volumes:
      - bitwarden_data:/data
      - bitwarden_ssl:/ssl
    environment:
      - SIGNUPS_ALLOWED=true
      - SIGNUPS_DOMAINS_WHITELIST=example.com
      - SMTP_HOST=smtp
      - SMTP_PORT=25
      - SMTP_SSL=false
      - SMTP_FROM=bitwarden@example.com
      - ADMIN_TOKEN=somestring
#     - DATABASE_URL=mysql://bitwarden:KX84fBJCTIp3lAHY@127.0.0.1:3306/bitwarden
#     - ENABLE_DB_WAL=false
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 110M
        reservations:
          cpus: '0.25'
          memory: 50M
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
      labels:
        - "traefik.docker.network=proxy_bitwarden"
        - "traefik.http.routers.bitwarden.rule=Host(`bit.example.com`)"
        - "traefik.http.routers.bitwarden.service=bitwarden"
        - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
  smtp:
    image: mhzawadi/postfix
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
      labels:
        - traefik.enable=false
    networks:
      - proxy_bitwarden
    environment:
      - POSTFIX_DOMAIN=example.com
      - POSTFIX_RELAYHOST=[smtp-relay.gmail.com]:25

  backup:
    image: bruceforce/vaultwarden-backup
    volumes:
      - bitwarden_data:/data
    networks:
      - proxy_bitwarden
    environment:
      - CRON_TIME=5 * * * *
      - TIMESTAMP=true
      - BACKUP_FILE=/data/backup.sqlite3
      - UID=0
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
      labels:
        - traefik.enable=false
