version: '3.5'

# docker stack deploy --compose-file stack-nextcloud.yml nextcloud

# networks:

configs:
  nextcloud_config.php:
    external: true

volumes:
  nextcloud:

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      labels:
        - traefik.enable=false
  notify_push:
    image: mhzawadi/notify_push
    ports:
      - "7867:7867"
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.50'
          memory: 30M
        reservations:
          cpus: '0.25'
          memory: 10M
      labels:
        - traefik.enable=false
    configs:
      - source: nextcloud_config.php
        target: /etc/nc_config.php
        uid: "0"
        gid: "0"
        mode: 0444
    volumes:
      - nextcloud:/data
