version: '2'
services:
  radarr:
    image: hotio/radarr
    container_name: radarr
    restart: always
    volumes:
      - radarr_config:/config
      - radarr_movies:/movies
      - radarr_torrents:/data
    ports:
      - "7878:7878"
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Europe/London
      - UMASK_SET=022 #optional
  sonarr:
    image: hotio/sonarr
    container_name: sonarr
    restart: always
    volumes:
      - sonarr_config:/config
      - sonarr_tvshows:/tvshows
      - radarr_torrents:/data
    ports:
      - "8989:8989"
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Europe/London
      - UMASK_SET=022 #optional
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - jackett_config:/config
      - jackett_downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  qbittorrent:
    image: gists/qbittorrent
    container_name: qbittorrent
    ports:
      - "8081:8081"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - radarr_torrents:/data
    environment:
      - UID=1001
      - WEB_PORT=8081
    restart: always
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Paris
    restart: always
volumes:
  radarr_movies:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/var/music/movies'
  radarr_torrents:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/var/music/torrents'
  radarr_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/mnt/lv_data/docker/radarr/config'
  radarr_downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/mnt/lv_data/docker/radarr/downloads'
  jackett_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/mnt/lv_data/docker/jackett/config'
  jackett_downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/mnt/lv_data/docker/jackett/downloads'
  sonarr_tvshows:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/var/music/tv_shows'
  sonarr_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/mnt/lv_data/docker/sonarr/config'
