---
services:
  radarr:
    image: hotio/radarr
    container_name: radarr
    restart: always
    volumes:
      - radarr_config:/config
      - radarr_movies:/movies
      - radarr_movies_kids:/kids_movies
      - radarr_torrents:/data
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/London
      - UMASK_SET=022 #optional
  sonarr:
    image: hotio/sonarr
    container_name: sonarr
    restart: always
    volumes:
      - sonarr_config:/config
      - sonarr_tvshows:/tvshows
      - sonarr_tvshows_kids:/tvshows_kids
      - radarr_torrents:/data
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/London
      - UMASK_SET=022 #optional
  prowlarr:
    image: hotio/prowlarr
    container_name: prowlarr
    restart: always
    volumes:
      - prowlarr_config:/config
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/London
      - UMASK_SET=022 #optional
  qbittorrent:
    image: gists/qbittorrent
    container_name: qbittorrent
    ports:
      - "8081:8081"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - radarr_torrents:/data
    environment:
      - UID=1000
      - WEB_PORT=8081
    restart: always
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Paris
    restart: always
volumes:
  radarr_movies:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/mnt/media/movies'
  radarr_movies_kids:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/mnt/media/kids_movies'
  radarr_torrents:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/mnt/lv_data/data/torrents'
  radarr_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/mnt/lv_data/docker/radarr/config'
  radarr_downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/mnt/lv_data/docker/radarr/downloads'
  prowlarr_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/mnt/lv_data/docker/prowlarr/config'
  sonarr_tvshows:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/mnt/media/tv_shows'
  sonarr_tvshows_kids:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/mnt/media/kids_tv_shows'
  sonarr_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/mnt/lv_data/docker/sonarr/config'
  lidarr_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/mnt/lv_data/docker/lidarr/config'
  lidarr_music:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/mnt/media/main'
